### ISSUE TITLE
Add `no-` options

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#124]
There's currently no way to unset a configured boolean setting via the command line.  E.g., if statusbar is turned on in the config, it can't be disabled without editing the config.  Add `no-` options for boolean flags.

**Comment by xxxserxxx** [comment]
@Tigerfyj, @talentlessguy -- if you have time, could I ask for translations for Chinese and Russian for the [five new flags here](https://github.com/xxxserxxx/gotop/commit/c691514a41a62da34f5e70f164729249184ca01b#diff-0e4b6e10c3d77270251a72b465b21823cede3df65822d5827d157ccc364e065c)? It would be really appreciated!

**Comment by Tigerfyj** [comment]
Sure, I will send a pull request in 2 or 3 days.

Thanks & Best Regards
Tiger Feng


xxxserxxx ***@***.***> 于2022年2月5日周六 00:35写道：
