### ISSUE TITLE
version is not displayed

### ISSUE THREAD

**Issue by tormath1** [xxxserxxx/gotop#140]
Hey, while upgrading `gotop` version on Gentoo (Guru), I found this regression:

##### gotop version:
`gotop -V`, or if built from source, `git rev-parse HEAD`

```
$ git rev-parse HEAD
e59e91847b44d98aa5148ea184c9755dda302c98
$ ./gotop -V
gotop 0.0.0 (Hadean)
```

##### OS/Arch:
Linux: `uname -or`, OSX: `sw_vers`; Windows: `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`
##### Terminal emulator: 
e.g. iTerm, kitty, xterm, PowerShell
##### Any relevant hardware info:
If the issue is clearly related to a specific piece of hardware, e.g., the network
##### tmux version:
`tmux -V`, if using tmux

Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs:

**Comment by xxxserxxx** [comment]
@tormath1 , this is as designed.  Rather than hard-coding the version number, it's embedded at compile time.  However, the README didn't explain how to set the version -- that's now addressed, and the **Building** section now includes those instructions.

Thanks for the report!
