### ISSUE TITLE
cli flags: Remove GNU style long flags

### ISSUE THREAD

**Issue by qlcom** [xxxserxxx/gotop#145]
remove flags starting with `--` (`--longflag`). instead use `-longflag` syntax as used in the go tool

**Comment by xxxserxxx** [comment]
I intentionally chose a library following GNU Argument Syntax, for better cognitive compatibility with GNU.  My reasoning is that:

1. The target audience for gotop is not only Go developers
2. The number of Linux users (used to GNU conventions) is larger than the number of Go developers
3. There are a number of benefits to the GNU conventions, such as unambiguous boolean argument concatination

I'm open to being convinced that the single-dash convention is better; I'll need a coherent argument that is more than just "the tool is written in Go, and so should use Go-style flags."

**Comment by qlcom** [comment]
jj

**Comment by qlcom** [comment]
this is not a GNU program
