### ISSUE TITLE
FreeBSD: ACPI thermal device not found error

### ISSUE THREAD

**Issue by mnrvwl** [xxxserxxx/gotop#152]
### Summary

`temp: no device hw.acpi.thermal.tz0.temperature found` error on startup.

ACPI system related parameters can be unreliable and depend heavily on hardware vendor implementations.

**Proposal**: silently tolerate missing `acpi_thermal` data if temperature module for builtin cpu sensor (e.g. `coretemp, amdtemp`) is loaded and available.

### System details

- System: `FreeBSD 12.2-RELEASE`
- CPU: `AMD Ryzen 9 3900X`
- Terminal: `/dev/pts/10`
- Version: `gotop-4.0.1`

### Steps to reproduce

```console
$ gotop -V
2020/11/14 17:33:08 temp: no device hw.acpi.thermal.tz0.temperature found
2020/11/14 17:33:08 temp: no device hw.acpi.thermal.tz0.temperature found
2020/11/14 17:33:09 temp: no device hw.acpi.thermal.tz0.temperature found
```

### Relevant logs

The `~/.cache/gotop/` logs are empty.

* * *

#### Notes

1. The system monitoring tool [glances](https://github.com/nicolargo/glances) was also tested: it does not seem to throw this error on startup.

**Comment by xxxserxxx** [comment]
Related to #130, I believe.

**Comment by Zeezee1210** [comment]
Is this not just a log line for missing _hw.acpi.thermal.tz0.temperature_ ? Doesn't fail though?
If there is **coretemp** or **amdtemp** installed then the _dev.cpu.0.temperature_ should be available and it registers that device.

These are the 2 entries looked for::
`var sensorOIDS = map[string]string{
	"dev.cpu.0.temperature":           "CPU 0 ",
	"hw.acpi.thermal.tz0.temperature": "Thermal zone 0",
}`

And this is when it's processed and produces the log line mentioned:
`	for k, _ := range sensorOIDS {
		idx := strings.Index(string(bs), k)
		if idx < 0 {
			log.Printf("temp: no device %s found", k)
		} else {
			rv = append(rv, k)
		}
	}
	return rv`

Looping though the OIDs it could miss the acpi entry, print the log line but then continue with the other OID.
Should only fail completely if both of those OIDs are missing.

**Comment by xxxserxxx** [comment]
Ok.  I don't see any reason why not to do it as suggested; it seems Caleb was trying to cover bases, not that we expect all devices to be available on FreeBSD.
