### ISSUE TITLE
Add man page

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#158]
Keep the `--help` brief, and add a man page to explain things like layouts and languages.

**Comment by gardotd426** [comment]
Yeah this would help a lot. I was wanting to edit the config file to set which temperature sensors I want shown, but I can only put one. Even though the comment in the config says you can use a list. Like:

```
# A list of enabled temp sensors.  See `--list devices`
temperatures=
```
Only, I can only put one device there. If I try to add more than one, it breaks. I've tried pretty much everything I can think of.
