### ISSUE TITLE
Incorrect ordering of CPU Core names.

### ISSUE THREAD

**Issue by mkrasnitski** [xxxserxxx/gotop#161]
CPU Core names are listed in pure alphabetical order, with CPU10 and CPU11 being listed before CPU2. It'd be better to list them using a more natural sort. Afaik this is a new issue in v4.1.0, it is not present in v4.0.1. Here's an image:

![image](https://user-images.githubusercontent.com/42564254/105756758-09512280-5f1b-11eb-9da8-47caafee1858.png)

##### gotop version: 
`gotop v4.1.0 (20210125T182337)`
##### OS/Arch: 
Arch Linux/5.10.10-zen1-1-zen
##### Terminal emulator: 
Alacritty

**Comment by xxxserxxx** [comment]
I don't believe there were any changes that would have caused this; if you get a chance to download v4.0.1 and try it, I'd be interested to see whether there's a difference.  I don't have more than 8 cores so I can't see myself. In any case, whether it's a regression or not, it's ugly the way it is so we'll get it fixed.
