### ISSUE TITLE
Runtime failure due to duplicate key in de_DE.toml

### ISSUE THREAD

**Issue by b0o** [xxxserxxx/gotop#166]
##### gotop version:
`aad28e93dbb84977a90ce9fab7c8c3c3744016d5`

I'm getting the following error upon running gotop:

```
2021/02/12 17:57:18 gopsutil reports Number of warnings: 1
2021/02/12 17:57:18 gopsutil reports Number of warnings: 1
failed to load language files: in file de_DE.toml: Near line 126 (last key parsed 'error.findlayout'): Key 'error.findlayout' has already been defined.
```

The issue looks to be the duplicate key here: https://github.com/xxxserxxx/gotop/blob/aad28e93dbb84977a90ce9fab7c8c3c3744016d5/translations/dicts/de_DE.toml#L125-L126

**Comment by xxxserxxx** [comment]
@b0o Good catch; thanks.
