### ISSUE TITLE
HelpMenu: non-ascii characters insert extra spaces

### ISSUE THREAD

**Issue by lourkeur** [xxxserxxx/gotop#167]
On the help screen, gotop typesets characters based on their byte length in UTF-8. This causes weird spacing in most languages that aren't English. This can be seen in German (`lö schen`, `wä hrend`), Esperanto (`paĝ o`) and upcoming French (`dé but`, `entiè re`) In Chinese this causes extra spacing between all ideographic characters. The main screen is not affected.

Termui has a Paragraph widget that can handle i18n typesetting better than the ad-hoc loop from 3 years ago. I'm working on it in b24c384ff5a661cb264585cc98fd87f6e0683795. It typesets but the window is sized in such a way that it sometimes eats the last line so I need to fix that.

##### gotop version:
gotop v4.1.1 (Hadean)

(not fixed in master afaict)
##### OS/Arch:
4.19.118 GNU/Linux (NixOS)
##### Terminal emulator: 
Sakura
##### Any relevant hardware info:
not applicable
##### tmux version:
not applicable

Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs: [empty]

![Capture d’écran de 2021-02-15 13-29-07](https://user-images.githubusercontent.com/15657735/107946915-f669c500-6f91-11eb-96c1-6852435a2da5.png)

**Comment by xxxserxxx** [comment]
@lourkeur outstanding report; thanks for all of the information.

**Comment by xxxserxxx** [comment]
@lourkeur Thanks for the work on this.  When do you see it eating the last line?

I'm pushing my version of your changes into master; the Paragraph struct seems to work well for all languages I've tried it with. Can you see if you can reproduce the issue you were seeing with that code?

**Comment by lourkeur** [comment]
@xxxserxxx Your candidate is good to go as far as eating the last line goes. The `textHeight` calculation needed to be adjusted by 1. Your patch did, mine didn't. That's language independent as well.

**Comment by xxxserxxx** [comment]
Thanks; your code was helpful for getting it done quickly.  Closing.
