### ISSUE TITLE
Wrong temperature value from it8721 ISA adapter

### ISSUE THREAD

**Issue by totoroot** [xxxserxxx/gotop#168]
Hey there,

Thanks for taking over this project and commiting to making it even better!

My ASUS motherboard delivers 3 temperature values from three sensors connected to an it8721. Surprinsingly gotop chooses to display the value of the disabled sensor, which reads -128.0ºC and is therefore not very useful.

The output of `sensors` for the it8721 ISA adapter is the following:
```
it8721-isa-0290
Adapter: ISA adapter
in0:           2.81 V  (min =  +0.10 V, max =  +2.22 V)  ALARM
in1:           2.74 V  (min =  +1.61 V, max =  +2.54 V)  ALARM
in2:         912.00 mV (min =  +2.84 V, max =  +1.48 V)  ALARM
+3.3V:         3.24 V  (min =  +5.93 V, max =  +0.62 V)  ALARM
in4:           1.20 V  (min =  +0.77 V, max =  +2.08 V)
in5:           2.53 V  (min =  +0.77 V, max =  +2.22 V)  ALARM
in6:           1.63 V  (min =  +2.93 V, max =  +0.16 V)  ALARM
3VSB:          3.86 V  (min =  +5.81 V, max =  +2.83 V)  ALARM
Vbat:          3.34 V  
fan1:         927 RPM  (min =   47 RPM)
fan2:         778 RPM  (min =   27 RPM)
fan3:         964 RPM  (min =   11 RPM)
temp1:        +38.0°C  (low  = -62.0°C, high = +105.0°C)  sensor = thermistor
temp2:        +33.0°C  (low  = -32.0°C, high = +95.0°C)  sensor = thermistor
temp3:       -128.0°C  (low  = -74.0°C, high = +85.0°C)  sensor = disabled
intrusion0:  OK
```

For `gotop --list devices` I get the following:
```
Temperatures:
	it8721_alarm
	it8721
	it8721_max
	it8721_min
	it8721_offset
	it8721_type
	it8721_alarm
	it8721
	it8721_max
	it8721_min
	it8721_offset
	it8721_type
	it8721_alarm
	it8721
	it8721_max
	it8721_min
	it8721_offset
	it8721_type
	k10temp_crit
	k10temp_crithyst
	k10temp
	k10temp_max
	nvme_composite_alarm
	nvme_composite_crit
	nvme_composite
	nvme_composite_max
	nvme_composite_min
	nvme_sensor1
	nvme_sensor1_max
	nvme_sensor1_min
	nvme_sensor2
	nvme_sensor2_max
	nvme_sensor2_min
```

I'd be fine with either temp1 or temp2 of the it8721 sensor, but as you can see, the only thing I can set in the config file is the sensor by its name 'it8721' which is the same for all three temperature readings. If I set it, the temp1 value is displayed.

I've tried ytop which lists the values of temp2 and temp3 but as this project got archived as well, I'm hoping for a fix, as I would really like to use gotop as my default system and activity monitor.

Thanks in advance!

##### gotop version:
gotop 0.0.0 (Hadean) --> installed with go get; therefore should be most recent version
##### OS/Arch:
5.10.15 GNU/Linux (NixOS Stable)
##### Terminal emulator: 
kitty
##### Any relevant hardware info:
n.a.
##### tmux version:
n.a.

Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs:
n.a.

**Comment by xxxserxxx** [comment]
Interesting. Since the ASUS is presenting three sensors under one name (or, gopsutil is grouping them under one name for some reason) gotop is probably just grabbing the first, or is overwriting the other two with the last.  I may need your help figuring out a way to choose the right temperature.

**Comment by totoroot** [comment]
Happy to help. I've got go installed on this Linux machine so let me know what tests I should run. I do not have experience with gopsutil however.
The motherboard is the ASUS M5A87 R2.0.

**Comment by totoroot** [comment]
As I'm changing my motherboard this issue is no longer relevant for me.
The new motherboard will have a B550 chipset and if any issues come up with gotop on that board I will report them separately.
Thanks again and I'll close this issue for now as I'll not be able to provide any additional information from now on.
