### ISSUE TITLE
Temperature scale in degrees Celsius

### ISSUE THREAD

**Issue by ignavan39** [xxxserxxx/gotop#170]
I think it would be cool to add the ability to choose a degree scale, this is especially true for my country.

I am preparing a Russian layout and I noticed this

**Comment by xxxserxxx** [comment]
To be clear, are you asking about the unit of measure (celsius vs fahrenheit)? Celsius is the default -- are you seeing fahrenheit? Or do I misunderstand your question?

**Comment by kitt3911** [comment]
No, I'm talking in general about choosing a temperature scale, let's say I can choose either Celsius or Fahrenheit

**Comment by xxxserxxx** [comment]
It's celsius by default; if you want fahrenheit, there's a command-line switch (`--fahrenheit` / `-f`). Or you can set the unit of measure in the config file. So, if I understand correctly, you specifically want a `--celsius` command-line option even though that's the default?

**Comment by xxxserxxx** [comment]
Hi @kitt3911 -- any response to my question?
