### ISSUE TITLE
Apple M1 support for gotop

### ISSUE THREAD

**Issue by mikemadden42** [xxxserxxx/gotop#177]
Hello, I was wondering if `gotop` has been tested on a device with Apple's M1? I did not see a `darwin/arm64` build on the releases [page](https://github.com/xxxserxxx/gotop/releases).  It would be really nice to have a binary that worked on the new Macs with the M1.

**Comment by xxxserxxx** [comment]
Closing in favor of #178, which has build failure information and an associated PR.
