### ISSUE TITLE
Feature request: Show disk temperatures

### ISSUE THREAD

**Issue by rare-magma** [xxxserxxx/gotop#182]
Hi,

It would be nice to have the disks temperatures added to the temp widget. 
Do you think it is possible to gather the data from s.m.a.r.t. or hddtemp perhaps?

Cheers!

**Comment by xxxserxxx** [comment]
I think the only challenge will be in getting sensor data for all platforms; disk data is already one of the more challenging things to support as there's high variability across OSes. It'll be easy if `gopsutils` supports temp; hard otherwise. Anyway, it's a good request, so accepted.
