### ISSUE TITLE
No more .deb files?

### ISSUE THREAD

**Issue by stpnwf** [xxxserxxx/gotop#198]
>**Prebuilt binaries**: Binaries for most systems can be downloaded from the github releases page. **RPM and DEB packages are also provided.**

I am trying to install gotop on my Ubuntu distro but I can't find any .deb files under any of the 4.0 + releases. Were they dropped?

**Comment by xxxserxxx** [comment]
Not intentionally. I re-worked the build process to automate it in GitHub and they probably got lost. I'll get them back in there.
