### ISSUE TITLE
Debs have bad version field

### ISSUE THREAD

**Issue by i0ntempest** [xxxserxxx/gotop#206]
Trying to install deb packages from releases results in:
```
dpkg: error processing archive ./gotop_v4.1.3_linux_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'gotop':
 'Version' field value 'vv4.1.3+git': version number does not start with digit
Errors were encountered while processing:
 ./gotop_v4.1.3_linux_amd64.deb
```
with dpkg 1.20.9

**Comment by gwrx** [comment]
quick workaround on ubuntu:

`
mkdir gotop
sudo dpkg-deb -R gotop_v4.1.3_linux_amd64.deb gotop/
sudo sed -i 's/vv4.1.3/4.1.3/g' gotop/DEBIAN/control
sudo dpkg-deb -b gotop
`

spit's out an installable deb

**Comment by xxxserxxx** [comment]
Thanks; #209 also reported this. The workflow has been updated and will hopefully produce a good deb next release.
