### ISSUE TITLE
Typo?  Celcius ==> Celsius

### ISSUE THREAD

**Issue by cclauss** [xxxserxxx/gotop#207]
./gotop/config.go:244: Celcius ==> Celsius
./gotop/build/gotop.conf:13: Celcius ==> Celsius

##### gotop version:
`gotop -V`, or if built from source, `git rev-parse HEAD`
##### OS/Arch:
Linux: `uname -or`, OSX: `sw_vers`; Windows: `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`
##### Terminal emulator: 
e.g. iTerm, kitty, xterm, PowerShell
##### Any relevant hardware info:
If the issue is clearly related to a specific piece of hardware, e.g., the network
##### tmux version:
`tmux -V`, if using tmux

Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs:

**Comment by xxxserxxx** [comment]
Thank you. These have been persistent bugs that keep getting piecemeal fixed, and I don't make it any better by repeatedly misspelling it in new changes.

**Comment by cclauss** [comment]
#210
