### ISSUE TITLE
precompiled deb package binary does not install on Proxmox 7.1

### ISSUE THREAD

**Issue by gsmitheidw** [xxxserxxx/gotop#209]
##### gotop version:
[gotop_v4.1.3_linux_amd64.deb](https://github.com/xxxserxxx/gotop/releases/download/v4.1.3/gotop_v4.1.3_linux_amd64.deb)
##### OS/Arch:
Proxmox 7.1-10
```Linux pve 5.13.19-3-pve #1 SMP PVE 5.13.19-7 (Thu, 20 Jan 2022 16:37:56 +0100) x86_64 GNU/Linux```
##### Terminal emulator: 
PowerShell/Kitty

The provided binary for AMD64 does not install on Proxmox. The following is reported:

```
dpkg: error processing archive gotop_v4.1.3_linux_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'gotop':
 'Version' field value 'vv4.1.3+git': version number does not start with digit
Errors were encountered while processing:
 gotop_v4.1.3_linux_amd64.deb
```

However it is possible to compile gotop 4.1.3 from source using the latest version of golang and the resulting binary works great.

**Comment by xxxserxxx** [comment]
Thanks for the heads-up. I've updated the build process so hopefully the next workflow will produce a good binary.
