### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by Bryan2333** [xxxserxxx/gotop#214]
I use gotop on my laptop.And it has a display problem like this
![2022-04-02 23-21-34屏幕截图](https://user-images.githubusercontent.com/31512600/161389989-59d99d4f-026e-4147-bb42-e89e6e72768e.png)
System info:
![2022-04-02 23-27-02屏幕截图](https://user-images.githubusercontent.com/31512600/161390051-17763549-b757-4631-b0b3-ed0ded9cfac5.png)

How can I solve this problem?

**Comment by xxxserxxx** [comment]
Did you find a resolution?

**Comment by Bryan2333** [comment]
yes , I installed noto-fonts and the problem was gone

**Comment by xxxserxxx** [comment]
Thanks for the confirmation; glad you got it working.
