### ISSUE TITLE
Nvidia flag is not loaded from config file

### ISSUE THREAD

**Issue by CyanLyan** [xxxserxxx/gotop#217]
Tested on two machines, `gotop --nvidia --mbps -c vice --write-config` was called and on both occasions the --mbps and the c flag were picked up but not the nvidia flag. I checked the config file and the nvidia=true line is present. Calling `gotop --nvidia` still causes the nvidia stats to be displayed.

##### gotop version:
d3fc311d68f2c3f4c0a8e2e0a95a0dbce7594669
##### OS/Arch:
5.16.19-76051619-generic GNU/Linux
##### Terminal emulator: 
Tested in Gnome terminal and Tilix
##### Any relevant hardware info:
NVidia 1050 ti v470.86 / 3070 driver v510
##### tmux version:
N/A

No error log generated

**Comment by xxxserxxx** [comment]
Would you mind posting your config? The nvidia line is sufficient.

**Comment by CyanLyan** [comment]
That area of the config is as follows -
`# Enable NVidia GPU metrics.
nvidia=true`
