### ISSUE TITLE
Selection fails to highlight

### ISSUE THREAD

**Issue by hackedXD** [xxxserxxx/gotop#226]
gotop version - gotop v4.1.4.r0.gcd0cf0f
os - Arch Linux 5.18.11-zen1-1-zen
Alacritty on Wayland

5.18.11-zen1-1-zen

![image](https://user-images.githubusercontent.com/63695721/179450528-4f7cb2f0-c9a1-4817-a871-1e4f1f3f74de.png)
![image](https://user-images.githubusercontent.com/63695721/179450556-71f37d86-d6ae-4bf9-a35d-a699ae9f7d6b.png)

**Comment by fanitriastowo** [comment]
Same here. It was fine before I upgrade to v4.1.4
 
gotop version: gotop v4.1.4 (Hadean)
os: manjaro kernel 5.15.54-1 
terminal: konsole
display: X11
![image](https://user-images.githubusercontent.com/8238046/179809255-7f6bb296-6b37-4eb1-8d01-9687d02c28cb.png)

**Comment by lourkeur** [comment]
Same here. I bisected it to these 4 commits cd44aab6, 3c148a4d97, c3aeb753d and 387c463eeeff. It looks like it comes from `termui` or another dependency.

Version: gotop v4.1.4 (Hadean) (via Nixpkgs)
OS: Linux 5.15.55, NixOS, 22.05 (Quokka), 22.05.20220718.3eb3df0
Terminal Emulator: [ate](https://github.com/andir/ate)
Display: X11 (dwm, picom)

![image](https://user-images.githubusercontent.com/15657735/179982412-0042a880-d5a0-4b8d-b08f-5bb8902c95f1.png)

**Comment by JC-Morph** [comment]
same issue
OS: Artix Linux x86_64
Kernel: 5.18.12-artix1-1
Terminal: st
![pic-selected-220726-1845-27](https://user-images.githubusercontent.com/14050519/181075664-b78c4c5f-d173-4743-bc08-722d95f97d48.png)

**Comment by mclang** [comment]
Arch, and i3 here... None of the color schemes work with Alacritty, Tilix or XFCE term.

**Comment by cmalvi** [comment]
same with gnome terminal

**Comment by lourkeur** [comment]
Still an issue in 4.2.0 (similar environment)

![image](https://user-images.githubusercontent.com/15657735/193155819-a6b7cd99-43be-4e2d-ab85-9da871f5d924.png)

**Comment by ChausseBenjamin** [comment]
Same with ST here:
![2022-12-05-113724_1051x1046_scrot](https://user-images.githubusercontent.com/19275615/205692251-fb8c0375-90e3-41bd-b680-85120f28b2d5.png)

**Comment by gardockt** [comment]
Oddly enough, this patch makes the selection work again for me:
```diff
diff --git a/termui/table.go b/termui/table.go
index 29e4c3f..e914a5d 100644
--- a/termui/table.go
+++ b/termui/table.go
@@ -98,7 +98,7 @@ func (self *Table) Draw(buf *Buffer) {
                if self.ShowCursor {
                        if (self.SelectedItem == "" && rowNum == self.SelectedRow) || (self.SelectedItem != "" && self.SelectedItem == row[self.UniqueCol]) {
                                style.Fg = self.CursorColor
-                               style.Modifier = ModifierReverse
+                               style.Modifier = 1 << 15
                                for _, width := range self.ColWidths {
                                        if width == 0 {
                                                continue
```

This issue seems to begin with commit c3aeb753d9355fcf3d5e6cbbdb892e61470e5abf, as a result of `termbox-go` dependency bump - reverting it resolves the issue. I couldn't, however, manage to replicate the issue with a simple program, as reverse modifier in this code works fine:

```go
package main

import (
	"image"
	"log"

	ui "github.com/gizak/termui/v3"
)

type Table struct {
	*ui.Block
}

func NewTable() *Table {
	return &Table{
		Block:       ui.NewBlock(),
	}
}

func (self *Table) Draw(buf *ui.Buffer) {
	self.Block.Draw(buf)

	style := ui.NewStyle(4)
	style.Modifier = ui.ModifierReverse
	buf.SetString(
		"hello",
		style,
		image.Pt(self.Inner.Min.X, self.Inner.Min.Y),
	)
}

func main() {
	if err := ui.Init(); err != nil {
		log.Fatalf("failed to initialize termui: %v", err)
	}
	defer ui.Close()

	p := NewTable()
	p.SetRect(0, 0, 50, 25)

	ui.Render(p)

	for e := range ui.PollEvents() {
		if e.Type == ui.KeyboardEvent {
			break
		}
	}
}
```

**Comment by Geometer1729** [comment]
@gardockt's fix works for me too

**Comment by DaL31** [comment]
Arch and i3 here. Problem still persists even though I have the newest version with the pr. Any ideas?

**Comment by xxxserxxx** [comment]
Yeah, I got a regression on my side too. I'm just commenting that I'm aware of the issue and am neither dead, nor ignoring it; I simply haven't had time to context switch back to gotop in a while.

**Comment by LouDnl** [comment]
Same issue here on different systems with the latest version.
