### ISSUE TITLE
gotop no longer works in urxvt, works fine in xterm

### ISSUE THREAD

**Issue by jgb** [xxxserxxx/gotop#227]
##### gotop version:
gotop v4.1.4 (20220715T163833)
##### OS/Arch:
Debian bookworm 5.18.0-2-amd64 GNU/Linux
##### Terminal emulator: 
rxvt-unicode

When I start gotop in rxvt-unicode, it shows the help window immediately explaining the shortcuts.
The only thing I can do then is hit q to exit, and gotop exists.
When I start gotop on the same machine in xterm, everything works fine.
The previous version didn't have this problem with urxvt.

**Comment by PieterjanMontens** [comment]
Same here, same version and similar environment.  This is what it looks like if I run `gotop -l kitchensink` :

![gotop_urxvt](https://user-images.githubusercontent.com/4528178/180550708-7222f095-57d3-4a8f-8a7e-7cf1674c838a.gif)

**Comment by jgb** [comment]
@xxxserxxx can confirm the latest 4.2.0 is still completely broken on rxvt.

**Comment by xxxserxxx** [comment]
@jgb Thanks, can you report what your TERM settings are, and whether @RockyBukake's hack works for you?

**Comment by jgb** [comment]
@xxxserxxx my TERM is set to `rxvt-unicode-256color`. Setting the TERM to something else like @RockyBukake suggests does fix the problem.

**Comment by xxxserxxx** [comment]
There haven't been any changes in termui in a while, but TBF, things are slow in gotop as well. The curse of the single-contributor project, I guess. 

It might not be a termui issue. It only seems to happen with rxvt-unicode and the rxvt-unicode terminfo combined -- the terminfo alone doesn't cause it, nor does urxvt with a different terminfo. I think you're probably right: one of the control characters is probably not being consumed properly by the terminal and is being passed through to gotop. 

On Arch, ncurses owns many of the terminfos, but rxvt-unicode is owned by the rxvt-unicode package. The repository for rxvt-unicode is in CVS(!!). The issue may be anywhere between there and gotop; sorry that I don't have any better instinct on where to start.
