### ISSUE TITLE
RX e TX Network for all time

### ISSUE THREAD

**Issue by Ser4ph4** [xxxserxxx/gotop#243]
Hello, is it possible to change the view of TX and RX network for all time? because when I reset the machine the value is reset, I would like it to be accumulative, is there a way to do that?

Grateful

**Comment by xxxserxxx** [comment]
There is not; it should be possible on Linux to get something similar since the last boot, but it may not be possible to do something that's portable.  gotop itself doesn't persist any data between runs -- it has no database.
