### ISSUE TITLE
gotop doesn't work in tmux

### ISSUE THREAD

**Issue by GustavoJCL** [xxxserxxx/gotop#256]
##### gotop version:
`gotop -V`, or if built from source, `git rev-parse HEAD`
gotop v4.2.0 (Hadean)
##### OS/Arch:
Linux: `uname -or`, OSX: `sw_vers`; Windows: `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`
Arch Linux 6.6.10-zen-1-zen GNU/Linux
##### Terminal emulator: 
e.g. iTerm, kitty, xterm, PowerShell
kitty
##### Any relevant hardware info:
If the issue is clearly related to a specific piece of hardware, e.g., the network
##### tmux version:
`tmux -V`, if using tmux
tmux 3.3a
Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs:
cat ~/.cache/gotop/errors.log
06:13:55 remote.go:74: Remote: no remote URL provided; disabling extension
06:13:55 temp_nix.go:35: error opening smart info for nvme0n1: unknown drive type
termbox: error while reading terminfo data: termbox: unsupported terminal
![image](https://github.com/xxxserxxx/gotop/assets/93671143/6bc8cca5-c24a-4e10-a208-80954f9e0e14)

**Comment by Kqzz** [comment]
if you run `echo $TERM` while in tmux, what is the output?

one potential fix is changing the `TERM` env variable while in tmux. I found an issue that appears related here that may offer some assistance: https://github.com/jesseduffield/lazygit/issues/570

**Comment by davidwincent** [comment]
Have the same problem,

```bash
❯ echo $TERM
tmux-256color

❯ gotop
panic: termbox: error while reading terminfo data: termbox: unsupported terminal

goroutine 1 [running]:
main.runUI()
        /home/dawndiy/workspace/golang/src/github.com/dawndiy/gotop/parts/app/go/src/github.com/dawndiy/gotop/main.go:535 +0x1144
main.main()
        /home/dawndiy/workspace/golang/src/github.com/dawndiy/gotop/parts/app/go/src/github.com/dawndiy/gotop/main.go:676 +0x20

```

Change value of TERM to start gotop successfully,

```bash
TERM=xterm-256color gotop

```

**Comment by GustavoJCL** [comment]
thanks, now gotop work fine
