### ISSUE TITLE
Relicensing to MIT

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#36]
See https://github.com/racket/racket/issues/1570. I would like to relicense gotop to the more permissive MIT license and doing so would require having any past and future contributors relicense their changes under the MIT license. The AGPLv3 license was originally chosen due to the drawille-go dependency and also the `smc.c` and `smc.h` files for macOS temperatures, both of which are GPL and which we would also need to migrate off of.

If you have contributed commits to gotop and are willing to relicense your commits under MIT, please comment on this issue with the following:

```
I, <name>, license past and future contributions to gotop under the MIT license.
```

Thanks!

(You may wish to unsubscribe from this issue after leaving your comment)

edit: updated the relicensing wording for clarity.

**Comment by xxxserxxx** [comment]
Pinging contributors here. If you agree to have the code that you have contributed to gotop be relicensed to MIT, please post your consent to relicense on this issue (#151). Thanks!

- [x] @mgamsjager
- [x] @omar-polo
- [x] @mattLLVW
- [x] @chiefy
- [ ] @f1337
- [x] @A-lxe
- [x] @tonylambiris
- [x] @whuang8
- [x] @serussell
- [x] @tie
- [x] @Lin-Buo-Ren
- [x] @gbrlsnchs
- [ ] @CodeLingoBot
- [ ] @zp
- [x] @0mp
- [x] @999eagle
- [ ] @h8liu
- [x] @panter-dsd
- [ ] @phpor

**Comment by xxxserxxx** [comment]
I, Alex Aubuchon, give permission to license my contributions to gotop under MIT.

**Comment by xxxserxxx** [comment]
Not that I hold a significant portion of the gotop's copyright, go ahead.

I, 林博仁(Buo-ren, Lin), give permission to license my contributions to gotop under MIT.

**Comment by xxxserxxx** [comment]
I, Gabriel Sanches, give permission to license my contributions to gotop under MIT.

**Comment by xxxserxxx** [comment]
I, Konstantin Konnov (panter_dsd), give permission to license my contributions to gotop under MIT.

**Comment by xxxserxxx** [comment]
I, Matt Melquiond, give permission to license my contributions to gotop under MIT.

**Comment by xxxserxxx** [comment]
I, Sophie Tauchert, give permission to license my contributions to gotop under MIT.

**Comment by xxxserxxx** [comment]
I, Tony Lambiris, give permission to license my contributions to gotop under MIT.

**Comment by xxxserxxx** [comment]
I, Matthias Gamsjager, give permission to license my contributions to gotop under MIT.

**Comment by xxxserxxx** [comment]
I, Ivan Trubach, license past and future contributions to gotop under the MIT license.

**Comment by xxxserxxx** [comment]
I, Mateusz Piotrowski, license past and future contributions to gotop under the MIT license.

**Comment by xxxserxxx** [comment]
I, Sean E. Russell, license past and future contributions to gotop under the MIT license.

**Comment by xxxserxxx** [comment]
I, William Huang, license past and future contributions to gotop under the MIT license.

**Comment by xxxserxxx** [comment]
I, Omar Polo, license past and future contributions to gotop under the MIT license.

**Comment by xxxserxxx** [comment]
I, Christopher Najewicz , license past and future contributions to gotop under the MIT license.

**Comment by xxxserxxx** [comment]
I, bryan , license past and future contributions to gotop under the MIT license.

**Comment by xxxserxxx** [comment]
Also: https://github.com/cjbassi/gotop/issues/151#issuecomment-586770583

**Comment by xxxserxxx** [comment]
The comment closed the ticket; I'm reaching out one last time to the folks who haven't responded, and will leave the ticket open until the 4.0 release.

**Comment by h8liu** [comment]
I, Lonnie Liu , license past and future contributions to gotop under the MIT license.

**Comment by xxxserxxx** [comment]
Bart Willems responded in the affirmative via email.

**Comment by wcdawn** [comment]
I, William Dawn, licence past and future contributions to gotop under the MIT license.

**Comment by xxxserxxx** [comment]
On May 20, 2020, in an attempt to close up the folks who haven't yet signed off, I sent the following email to the contributors listed (emails hidden) at the bottom of this post. Per the email, the cut-off date is June 03, 2020.

> Since Caleb stopped developing gotop[1], I've taken over maintainer-ship of
> the project. I'm requesting that each of you to take a few minutes 
> and give your approval on github for the re-license. The ticket is here:
> 
>    https://github.com/xxxserxxx/gotop/issues/36
> 
> Thanks again for your contributions, and the time you take to comment on
> the ticket will be appreciated.
> 
> 
> More information
> ----------------
> 
> - The current gotop license is AGPL.
> 
> - I am re-licensing gotop under MIT 3-clause.
> 
> - [1] Caleb has stopped using Go, and has switched to Rust.  He has
>   re-implemented gotop in Rust, and called it ytop; you can find it
>   here:
>      https://github.com/cjbassi/ytop
>   You can see Caleb's announcement on his gotop repository, and his link
>   to my repository. Most (many?) downstream distribution channels have 
>   been redirected to the new repository.
> 
> - Caleb opened ticket #151 (https://github.com/cjbassi/gotop/issues/151)
>   for the re-license to MIT in June, 2019. As no more development is
>   happening on that repository, I'm asking that approvals be made on the
>   cloned ticket.
> 
> - You are being contacted because there's a commit in the project git
>   history in your name.
> 
> - Caleb referenced a similar ticket from the Racket project, which
>   explains their change; their ticket (rationale and explanation) aligns
>   with this change.
>      https://github.com/racket/racket/issues/1570
> 
> - In alignment with the Racket post, non-response will be taken as
>   implicit approval of the change.
> 
> Caleb posted his request nearly a year ago.  I'm making a good-faith
> final effort to reach out to the remaining folks for explicit approval.
> Prior to the next major release (4.0) which will happen no sooner than
> two weeks from now, a copy of this email and list of recipients (with
> emails hidden) will be added to the ticket, and the ticket will be
> closed.
> 
> 
> Nano-FAQ
> --------
> 
> Q: What if I don't agree?
> A: I'll revert your contribution(s) and provide an alternative solution.
> 
> Q: Wouldn't this delay the 4.0 release and bring me bad karma?
> A: Yes. Yes, it would. It would also make me sad.
> 
> Q: Why would I do this? Aren't I a good person?
> A: Yes! You're the *best* person. I don't know why we're even having
>    this conversation.

Recipients:
- CodeLingo Bot <bot@...>
- Bart Willems <bwillems@...>
- Michael R Fleet <f1337@...>
- John Muchovej <git@...>
- Jeffrey Horn <jeffreyh@...>
- Jaron Swab <jrswab@...>
- Lonnie Liu <liulonnie@...>
- Markus Peloquin <markus@...>
- Mathieu Tortuyaux <mathieu.tortuyaux@...>
- matt LLVW <matt.llvw@...>
- MaxSem <maxsem.wiki@...>
- PanteR <panter.dsd@...>
- Brian Mattern <rephorm@...>
- Kraust <secretdragoon@...>
- Pzp <thatguyzp@...>
- HowJMay <vulxj0j8j8@...>

**Comment by ionlights** [comment]
Sorry, didn't see this until now. 

```
I, John Muchovej (@ionlights), license past and future contributions to gotop under the MIT license.
```

**Comment by markuspeloquin** [comment]
I, Markus Peloquin, license past and future contributions to gotop under the MIT license.

And thank you for adopting a permissive license.

**Comment by xxxserxxx** [comment]
v4.0.0 has been released, and with it, the relicensing is complete.  Thanks to everyone who responded.
