### ISSUE TITLE
Feature Request: Add option to show only widget passed through commandline argument

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#39]
Sometimes, The usecase is such that we only need to monitor _one_ thing. For example, We may need to only see the network widget or memory widget.

Hence, Add a command-line option that takes the name of the widget and displays only that widget.

This will be helpful in case of tiled terminals with small terminal area.

A sample Command line interface could look like:

`gotop --widget=network`

`gotop -w network` 

Original ticket https://github.com/cjbassi/gotop/issues/155
Original submitter @xypnox

**Comment by xxxserxxx** [comment]
This feature would be very usefull, if possible please allow multiple like -w=CPU,Memory,Network,Processes or similar.
This way it would be able to hide the Temperature-boxes for example, which are usually empty on my VMs anyway.

**Comment by xxxserxxx** [comment]
@xypnox -- addressed in release 3.2.0 (on this repository), through the configurable user interface.  The way you'd do it with the release is:
```
echo net | gotop -l -
```
The configurable UI feature allows you to do more than this, including creating a layout file with (in this case) only a single widget, putting it in (say) a file called `$XDG_CONFIG_DIR/gotop/net-only` and then running `gotop -l net-only`. The README has more information about this feature.

Original ticket cjbassi/gotop#155

**Comment by xypnox** [comment]
Thanks for adding the feature. Would surely use this!

**Comment by xxxserxxx** [comment]
Closed by 4247e9339e (or thereabouts); release 3.1.0, binaries available in the releases tab.
