### ISSUE TITLE
Option to limit CPU usage

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#41]
Not sure if controlling the hardware is in the scope of this project or not. If not, feel free to close. 

I have been facing a shutdown of my system when CPU overheats. More information can be found on [this SuperUser question](https://superuser.com/q/1345775/103134).

Original ticket https://github.com/cjbassi/gotop/issues/161
Original submitter @santosh

**Comment by xxxserxxx** [comment]
Upstream was closed by @santosh

**Comment by santosh** [comment]
Well, I closed that because there was no reply from the author. 
You can continue working on it if you want.

**Comment by xxxserxxx** [comment]
@santosh , Caleb is not working on his branch of gotop any longer. I'm continuing development here.

Are you still having this issue?  If so, I'll re-open it.

**Comment by santosh** [comment]
This was not an issue. It was a feature request.
