### ISSUE TITLE
Can we get an option to display network usage always as mbps?

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#46]
Currently it uses Bytes (not bits) and it's different magnitudes. Would be nice if we could lock it always to measure mbps.

**Comment by xxxserxxx** [comment]
Clone https://github.com/cjbassi/gotop/issues/174
@Gonza21Gd  FYI

**Comment by xxxserxxx** [comment]
@Gonza21Gd, can you clarify the request?  Do you want it Gb instead of GB?  Or do you mean that, it doesn't scale?  Or that the scale is fixed on the command line?

**Comment by Gonza21Gd** [comment]
I didn't mean the total data transferred, that's fine as GB. I meant the real time transfer speed, which currently is as RX or TX (as bytes), and not bits per second.

**Comment by xxxserxxx** [comment]
@Gonza21Gd Ok, so I'm looking at this and I want to make sure I understand the request.

Currently, the net widget shows:
```
Total RX: <whatever>
RX/s:       x.y <units>/s
```
Same for TX.  You want to leave the Total alone, but have the `RX/s` be `mbps`, and `<units>/s` ... just be blank because it's redundant.  So it'd look like:
```
Total RX: <whatever>
mbps:       x.y
```
Is that accurate?  I ask because, unless I'm downloading something, my RX/s is usually under (or around) 100 Kbps, so rounding would case this to be 0.1mbps most of the time.
