### ISSUE TITLE
Help screen and statusbar font color does not obey theme

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#47]
Required information:

- gotop version (`gotop -V`): 3.0.0
- The output of `uname -a`: Linux vagrant 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Terminal emulator (e.g. iTerm or gnome terminal): 
- Any relevenat hardware info: 
- tmux version if using tmux: 

Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs:

### Issue:

The help text does not obey color theme.

### Reproduction steps:

1. Use a terminal with white background
2. Run `gotop --color default-dark --statusbar`
3. Notice the status bar time is white over white
4. Press <kbd>?</kbd>
5. Notice the help text is white over white

### Actual behavior:

When using `gotop --color default-dark` the help text is still white over white as shown in this screenshot:
![image](https://user-images.githubusercontent.com/2405099/67385934-b6acec00-f59c-11e9-90ac-45bdcde0747e.png)

### Expected behavior:

Expecting the text to be readable - black over white.

**Comment by xxxserxxx** [comment]
Clone https://github.com/cjbassi/gotop/issues/175
@DannyBen  FYI

**Comment by DannyBen** [comment]
Does this mean that this fork intends to be the successor?

**Comment by xxxserxxx** [comment]
@DannyBen **I** intend it to be the successor, and have both spoken at length with Caleb and pinged the owners of other forks and other contributors; nobody else has offered to take primary maintainership, so, yeah.  I'm going to work at getting the distributions switched over to this for.  Here's a bit of copypasta, since this question is (understandably) coming up frequently:

Caleb is not maintaining gotop any longer, but also doesn't want anybody else maintaining his repository, nor is he comfortable with moving issues. I'm continuing development and maintenance of gotop, so I've forked and copied the tickets so that I can keep working on them.

See [this issue](https://github.com/cjbassi/gotop/issues/187) for more information.

**Comment by xxxserxxx** [comment]
@DannyBen there have been [new releases](https://github.com/xxxserxxx/gotop/releases), as well.
