### ISSUE TITLE
Linux distro packages

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#5]
I think you should try to get this into Linux disros.

So maybe we can track this here?

Original issue https://github.com/cjbassi/gotop/issues/33
Original submitter @rugk

**Comment by xxxserxxx** [comment]
Do you mean get the application into the official repos of certain distros? Or do you mean we should build packages for different distros like .deb packages? Or something else?

I'm only familiar with Arch Linux so let me know  what I need to do for other distros.

Also, leave suggestions for which distros we should set things up for.

**Comment by xxxserxxx** [comment]
> Do you mean get the application into the official repos of certain distros?

Yes.

**Comment by xxxserxxx** [comment]
Well as far as Arch Linux goes, applications get voted into the official 'community' repo based on how many votes it gets in the AUR, so there's that. Don't know about other distros but I'll do some research.

Thanks for opening this issue btw! I like the idea and hopefully we can make some progress on it.

**Comment by xxxserxxx** [comment]
@cjbassi 

I will package gotop for Frugalware Linux , official main repo.
Testing it right now  and I really like it , good job :)

I just have a problem on my EPYC box , opened #34 about.

**Comment by xxxserxxx** [comment]
I started to maintain an [ebuild](https://gitlab.com/chaoslab/chaoslab-overlay/tree/master/sys-process/gotop) in my [overlay](https://gitlab.com/chaoslab/chaoslab-overlay). Any distros that uses portage system (Gentoo, Funtoo, Calculate, etc.) can easily import and _emerge_ it.

BTW, thanks for the application, it's working well on my machines.

**Comment by xxxserxxx** [comment]
I have an APKBUILD for an Alpine Linux package here:

https://github.com/Head-on-a-Stick/configs/blob/master/APKBUILD.gotop

It should also work as an Arch Linux PKGBUILD with minor changes.

**Comment by xxxserxxx** [comment]
I'm going to use this ticket for packagers.

As you (may have) seen, Caleb's busy with a rewrite of `gotop` called `ytop`, and he's decided to stop working on `gotop.` He's marked his fork as "Unmaintained."  Caleb's indicated he'd rather development continue in a fork rather than in his repository, so I've been continuing development in my fork.   I've been merging pull requests that have been open since early last year, and adding features.

If you are still interested in helping with coordinating with the distributions, please let me know.  I'd like to better coordinate the releases and downstream updates on distributions.

- @abucodonosor -- are you still working on a Gentoo-derived distribution?
- @Head-on-a-Stick -- ditto; are you doing Alpine packaging?

**Comment by Head-on-a-Stick** [comment]
> are you doing Alpine packaging?

No, I don't use Alpine Linux any more.

But the package is in Alpine's *community* repository:

https://pkgs.alpinelinux.org/packages?name=gotop&branch=edge

**Comment by xxxserxxx** [comment]
> But the package is in Alpine's _community_ repository:

Thanks.

**Comment by xxxserxxx** [comment]
Closing in favor of #68
