### ISSUE TITLE
output snapshot as json

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#50]
__ask__

CLI arg to output snapshot of system metrics (CPU, mem, disk, et al.) as JSON

__why__

Diffing. For example, let's say your machine feels laggy. You open gotop and things look pretty normal, but you don't remember the metrics from the last time you opened gotop, so unless something is very obviously wrong (machine is super hot, runaway process is hogging memory) you won't have any useful comparisons to make.

Whereas, with the JSON output option, you could just `gotop --json > gotop-metrics-<date>.json` to establish a baseline and then, when things get laggy, compare your current situation to the baseline.

**Comment by xxxserxxx** [comment]
@zachvalenta -- active development has moved to this fork; responding here.

What would you think about gotop [exporting metrics](https://prometheus.io/) that you could `curl` to get a snapshot?

I've been thinking about this for a while now.  Short term, it would allow your snapshots.  Medium term, it'd be trivial to expose this through a proxy and remotely monitor machines.  Long term, I'd like to add "remote" widgets, so you can connect gotops running on different machines.  There'd be virtual devices that, e.g., the CPU widget could use which would be pinging a remote gotop and displaying it locally.

Would that satisfy your request?

**Comment by xxxserxxx** [comment]
This will be in 3.4.0.  It's available on the v3.4.0 branch for early access, and it looks like this (ignore the tmux artifacts):

[![Metrics](https://asciinema.org/a/spxxHKMf3MBR8OfUYwsbZurXq.png)](https://asciinema.org/a/spxxHKMf3MBR8OfUYwsbZurXq)

**Comment by zachvalenta** [comment]
This is very cool. Looking forward to 3.4 :)
