### ISSUE TITLE
NVIDIA card video temperature 

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#52]
I have a card video from Nvidia installed on my pc including driver. How do I show her on gotop? The command that show temperature is
`nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader`
There's one way to put this command over gotop configurations?

**Comment by xxxserxxx** [comment]
Related #42

**Comment by xxxserxxx** [comment]
Thank you; I'll check those out.  The other two pull requests that had been submitted used rai-project/nvidia-smi.  mxpv/nvml-go is still using C bindings, but if it pulls in fewer bizarre dependencies than NVIDIA's Go bindings, it'd be preferable.

gosensors looks great!  lmsensors may solve all of the device issues by itself; that's pretty exciting.

Thanks again

**Comment by xxxserxxx** [comment]
Closing this in favor of #52, which has broader scope.

**Comment by talentlessguy** [comment]
@xxxserxxx um, why do you close the issue and point to this same issue, I got confused

**Comment by xxxserxxx** [comment]
@talentlessguy I meant to point it to #42.  I got the numbers wrong.
