### ISSUE TITLE
Invalid --version in deb package

### ISSUE THREAD

**Issue by DannyBen** [xxxserxxx/gotop#55]
Running `gotop --version` gives the wrong version number after installing from the deb package on GitHub releases page.

```shell
$ sudo dpkg -i gotop_3.3.1_linux_amd64.deb
(Reading database ... 177421 files and directories currently installed.)
Preparing to unpack gotop_3.3.1_linux_amd64.deb ...
Unpacking gotop (3.3.1) over (3.3.1) ...
Setting up gotop (3.3.1) ...

$ gotop --version
3.1.0
```

---
Required information:

- gotop version (`gotop -V`): downloaded 3.3.1, received 3.1.0
- The output of `uname -a`: Linux vagrant 4.15.0-88-generic # 88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Terminal emulator (e.g. iTerm or gnome terminal): NA
- Any relevenat hardware info: NA
- tmux version if using tmux: NA

**Comment by xxxserxxx** [comment]
Huh. Strange; the version in the source for that tag is correct.  I'm still coming up to speed on the packaging, though, so I probably made a mistake.  I'll see if I can rebuild and update the RPM in that release.

**Comment by xxxserxxx** [comment]
Fixed the make script; the `nfpm` spec was incorrect for how I was building.  New archives have been uploaded to the **same** release (3.3.1).  @DannyBen, thanks for the heads-up.

**Comment by DannyBen** [comment]
Confirmed as fixed.
