### ISSUE TITLE
Colors with dash in the name are broken

### ISSUE THREAD

**Issue by DannyBen** [xxxserxxx/gotop#57]
```shell
$ gotop --color default-dark
failed to parse cli args: failed to read colorscheme file: open /home/ubuntu/.config/gotop/default-dark.json: no such file or directory

$ gotop --color solarized16-dark
failed to parse cli args: failed to read colorscheme file: open /home/ubuntu/.config/gotop/solarized16-dark.json: no such file or directory

$ gotop --color solarized16-light
failed to parse cli args: failed to read colorscheme file: open /home/ubuntu/.config/gotop/solarized16-light.json: no such file or directory
```

---

Required information:

- gotop version (`gotop -V`): 3.3.1
- The output of `uname -a`: Linux vagrant 4.15.0-88-generic # 88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by xxxserxxx** [comment]
Thanks for the report @DannyBen. Although it's labeled for v3.4.x, v3.4 has some fairly significant features and I'm going to let it soak for a bit before releasing it; I'll probably do a v3.3.2 bug-fix release before then if I can knock out a couple more bugs.
