### ISSUE TITLE
Cannot switch processes with keys

### ISSUE THREAD

**Issue by talentlessguy** [xxxserxxx/gotop#61]
Required information:

- gotop version (`gotop -V`): 3.4.0
- The output of `uname -a`: `
Linux v1rtl-pc 5.4.18-1-MANJARO #1 SMP PREEMPT Thu Feb 6 11:41:30 UTC 2020 x86_64 GNU/Linux`
- Terminal emulator (e.g. iTerm or gnome terminal): konsole

When I try to switch processes with arrow keys or mouse, nothing happens.

Here's a gif for comparing 3.4.0 gotop, and 3.0.0 gotop:

![gotop](https://user-images.githubusercontent.com/35937217/75347141-33383a00-58b1-11ea-9ae8-99a669e46bcf.gif)

**Comment by xxxserxxx** [comment]
Thanks for the report; this is a clone of #59

**Comment by xxxserxxx** [comment]
And I just pushed a fix for #59 to the v3.4.x branch which addresses this.
