### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#63]
Current steps for a release:

### gotop
1. Update Version in main.go 
2. Update CHANGELOG.md
3. Tag
4. Push everything
5. ./make.sh
6. Create github release

### Homebrew
1. Change homebrew-gotop
```
curl --output - -L https://github.com/xxxserxxx/gotop/releases/download/v3.3.2/gotop_3.3.2_linux_amd64.tgz | sha256sum
curl --output - -L https://github.com/xxxserxxx/gotop/releases/download/v3.3.2/gotop_3.3.2_darwin_amd64.tgz | sha256sum
```

### AUR
1.  Update aur/PKGBUILD
2.  namcap PKGBUILD
3.  makepkg
4.  makepkg -g
5.  makepkg --printsrcinfo \> .SRCINFO
6.  Commit everything
7.  push
```
curl -L https://github.com/xxxserxxx/gotop/archive/v3.3.2.tar.gz | sha256sum
```

### AUR-BIN
1.  Update aur-bin/PKGBUILD
2.  namcap PKGBUILD
3.  makepkg
4.  makepkg -g
5.  makepkg --printsrcinfo \> .SRCINFO
6.  Commit everything
7.  push aur-bin

**Comment by ionlights** [comment]
Per some of what's been said in #60, GitHub Actions could do all of this (as far as I understand). I'm willing to give this a go, I think; though it may take some time as GitHub Actions have to be tested in an odd fashion.

**Some caveats:**
- I don't have access to Windows, so I know I can't do testing there.
- Currently, the only Linux distro I can test on is Arch Linux.
- Currently, GitHub Actions __only__ supports Ubuntu LTS 16/18. https://github.com/actions/virtual-environments

I have another project with some committers working on making changes to different repositories and uploading those changes. Can update on that (hopefully) in the next week or two. This would simplify things with `homebrew-gotop`.

**Comment by xxxserxxx** [comment]
Thanks.  I also updated both aur and aur-bin; thanks for the prompt -- I didn't realize I had write access.

Updated the steps.

**Comment by xxxserxxx** [comment]
This is set up; thanks for the pointer @ionlights.

Using Github Actions makes me long for Bitbucket pipelines, but I eventually figured it out.  I ended up having to build a custom docker image for the Darwin cross-compile, and my own action to use it, but the end result is:

- Every commit performs a test build (unit tests to come)
- Every tagged commit kicks off a job that builds the binaries and creates a draft release with the artifacts attached

Because of the second point, releasing now only requires me to add the release description and publish.  Far easier than what I was doing, but that's CI for you.

I will forever resent both Atlassian/Bitbucket and Microsoft/Github for creating workflow systems that can't be tested locally on a laptop.  The repository history looks stupid now because there's no way to test actions without committing changes.  If I'd have been smart, I'd have forked the repo and done the testing there... oh, except github (unlike bitbucket) won't let you fork your own projects (unless you pay them money).  I'm not going to complain too much about that last part; this is mostly a free service, but still... providing no way to test locally is just *stupid.*  Rant over.

**Comment by ionlights** [comment]
Awesome! Glad to hear they're automated now. 🙂 Were you able to get the linkages for xxxserxxx/homebrew-gotop to work as well? So it dumps the SHA and version number?

Also, I'll give the PR i made over there a go in a bit to see if you can just change that number instead of changing it in 3-4 places. 😅
