### ISSUE TITLE
[feature-request] Add MacOS build to homebrew-core

### ISSUE THREAD

**Issue by ionlights** [xxxserxxx/gotop#69]
Started adding MacOS info in https://github.com/Homebrew/homebrew-core/pull/51012

Based on discussion taking place there (and reading the "Formula Cookbook"), it seems clear what needs to happen – and that this needs to be tested on a MacOS system.

https://docs.brew.sh/Formula-Cookbook

I'm willing/able to do this, but can't until this weekend. Some things that I need to know are:
- What's included in the `.tar.gz` you package? Based on what I see with https://github.com/cjbassi/gotop/archive/3.0.0.tar.gz – that's just a link to the v3.0.0 source code zipped in a gzip.
- What system command should I need to compile the package from source?
   - What version of go do I need?
   - How often does this version change?

I think these are solid questions to get me started. If there's somewhere to point me, that works as do fleshed out answers to this. 🙂

**Comment by xxxserxxx** [comment]
The source tar.gz is something github auto-generates; it's a repository snapshot at a specific revision/tag, the same as a `git clone --depth 1 <repo>` but without the `.git` directory.  As you say, it's the sourcecode.

The system command for MacOS should be:
```
CGO_ENABLED=1 go build -o gotop ./cmd/gotop
```
Darwin needs CGO for the headers to access the system devices.  This command is run from within the source code directory.

The version ... doesn't that change with every release?  The currently released version is 3.3.2, although by the time we figure this out, it'll be 3.4.x or 4.0.  I had to bump the version a bunch of times to test the workflow, and I'm so far into the 3.4's now, and the hand-over is mostly "official", so I may just jump to 4.0.0.

Semver: minor releases monthly.  Major releases, quarterly.  The safest bet is "monthly".  

I understand Homebrew wants to set expectations, so use "monthly."  However, for anyone who is searching for "release schedules" and comes across this: I have no set schedule for releases, and right now I have time so I'm powering through the backlog. I was releasing multiple times a week until recently; at 3.3.2 I slowed down to soak releases and work on CI, and now that it's getting into distributions I'm going to be more circumspect about the major feature changes.  Eventually I won't have as much free time and I can see things slowing down to quarterly releases, even for (non-critical) bug fixes.  A lot depends on how many people contribute pull requests -- I'll always prioritize those and make sure they get out.  However, agree with the Go team's philosophy: it goes out when it's ready.

**Comment by xxxserxxx** [comment]
I released v3.5.1, a bugfix release, on 2020-04-09.

**Comment by alebcay** [comment]
A change for updating the `gotop` formula in Homebrew has now been proposed at https://github.com/Homebrew/homebrew-core/pull/54014. As far as I can tell, this new version should work without any issues. Please feel free to test it and let us know if there are any particular issues in the copy of `gotop` that we ship.

**Comment by ionlights** [comment]
@alebcay Thanks! This fell pretty far on my task list. 😕 

Can confirm that `homebrew/core` has `v3.5.2` available. @alebcay What I was originally focusing on was helping @xxxserxxx automate this process; do you think you could elaborate on how he might be able to do that? (You're clearly more familiar with `brew` than I am. 😅) 

@xxxserxxx I don't think the `tap` is necessary anymore. (Especially if you can open PRs to `homebrew` automatically.)

**Comment by alebcay** [comment]
Yes, Homebrew does have some tooling to make submission of updates easier. Primarily,
- `bump-formula-pr` is a `brew` subcommand that automates the formula version bump commit and opens a PR. If the build process (dependencies and commands to be run) remains unchanged, all you need to do is provide the new URL to the tarball and the new SHA256 checksum of that tarball, e.g.:
```
brew bump-formula-pr gotop \
    --url="https://github.com/xxxserxxx/gotop/archive/v3.5.2.tar.gz" \
    --sha256="d175d370491c1d1b98c8cd1015674f5cfc04d3dbe6ea4a528b641698f0fafb34"
```
- [Homebrew bump formula action](https://github.com/marketplace/actions/homebrew-bump-formula) via GitHub Actions, which allows for a PR to immediately be opened with Homebrew whenever a new version tag of `gotop` is pushed.

**Comment by xxxserxxx** [comment]
> Homebrew bump formula action via GitHub Actions, which allows for a PR to immediately be opened with Homebrew whenever a new version tag of gotop is pushed.

This is excellent, as gotop's CI is using github actions; it's exactly what I was hoping for, thank you.

Are there any gotchas I should watch for when major revision changes happen?

**Comment by alebcay** [comment]
> Are there any gotchas I should watch for when major revision changes happen?

Not really, I think. Just keep in mind that the action will only modify the `url` and `sha256`. If the steps involved for building (e.g. commands that need to be run) change, you will probably need to follow up with additional commits in the PR that the action opens. You may also need to make such changes if the program behavior that is tested in the `test do` block of the Homebrew formula changes.

**Comment by xxxserxxx** [comment]
Ok. Thanks for the input @alebcay.

The README on master has been updated, and I've added a deprecation flag on the tap; I'll delete the repo in a month or so.  I've added `homebrew-bump-formula` to the release action (it still needs to be tested -- next release), so I'm closing this ticket.

Thanks for all of the help @alebcay & @ionlights .
