### ISSUE TITLE
gotop should throw an error while trying to use a non-installed plugin

### ISSUE THREAD

**Issue by talentlessguy** [xxxserxxx/gotop#77]
`gotop` should throw an error of a missing plugin instead of silently launching with a hanging execution

##### gotop version:
3.5.0
##### OS/Arch:
Linux: GNU/Linux x64
##### Terminal emulator: 
Konsole
##### Any relevant hardware info:
NVIDIA GT 740M

Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs:

```
20:21:37 main.go:473: no plugin nvidia.so found in current directory
20:21:37 main.go:478: no plugin /home/v1rtl/.config/gotop/nvidia.so found in config directory
```

**Comment by xxxserxxx** [comment]
Addressed by c24562d6.  gotop exits with an error code and a message to check the error file rather than running without the requested extension.
