### ISSUE TITLE
Gotop won't install

### ISSUE THREAD

**Issue by iliyan61** [xxxserxxx/gotop#87]
During install it errors out with: 

`curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "gotop"
Download failed: https://github.com/xxxserxxx/gotop/releases/download/vv3.5.1/gotop_vv3.5.1_darwin_amd64.tgz
`

any ideas on when this will be fixed?

**Comment by tormath1** [comment]
Hi, 

This URL but it seems to be a wrong one (duplicate `v` on the version number).

From the release page, the URL is
```
https://github.com/xxxserxxx/gotop/releases/download/v3.5.1/gotop_v3.5.1_darwin_amd64.tgz
```

**Comment by xxxserxxx** [comment]
@iliyan61 How were you trying to install?  What platform are you on?

**Comment by iliyan61** [comment]
@tormath1 I'm just running brew tap and brew install and then the name as per the instructions so it means the script or repo has a issue with the wrong domain being inputted.

**Comment by iliyan61** [comment]
@xxxserxxx macOS Mojave with home brew I tried on two different computers. As you can see there's an extra 'v' in the domain that home-brew is trying to retrieve gotop from.

**Comment by xxxserxxx** [comment]
@iliyan61 Thanks for the information.  Yes, I see it now; the git pipeline for updating the recipe had a flaw.  Thanks for reporting this; I don't have a Mac to test this with.

**Comment by xxxserxxx** [comment]
Fix pushed as https://github.com/xxxserxxx/homebrew-gotop/commit/4781815d0607cccb1b004bcab7809d2c8222b09d

**Comment by iliyan61** [comment]
@xxxserxxx I assume it'll probably still error out using brew or git install on linux.
