### ISSUE TITLE
something wrong with versioning

### ISSUE THREAD

**Issue by mighty9245** [xxxserxxx/gotop#89]
i was reinstalling gotop from aur and noticed that version got updated to DELETED. a little investigation and i noticed that cloning repo and running `git describe --long --tags` (what basically aur pkgbuild is doing) returns this weird thing: DELETED-4-g84ec9e4

can you please do something with this so the package will have a fancy version?

**Comment by xxxserxxx** [comment]
Which package do you use?  When I install from AUR, both gotop and gotop-bin give me version 3.5.1.  I have no control over the `gotop-git` package, so I don't know what's going on there.

**Comment by mighty9245** [comment]
i'm using exactly `gotop-git...

**Comment by xxxserxxx** [comment]
github master was pointing at the wrong branch.  It's now pointing at the v3.6 release candidate (active development branch), and the gotop-git package now pulls the right code.

Please reinstall and see if you get version 3.6.0 -- it's not the *real* v3.6.0, but a pre-release version.

**Comment by mighty9245** [comment]
yup, got `local/gotop-git 3.5.1.r21.gdfa7098-1` - latest available tag + latest available commit. i guess it's fine now, thank you!
