### ISSUE TITLE
Rounding Issue

### ISSUE THREAD

**Issue by cking** [xxxserxxx/gotop#90]
[this is an updated copy of  cjbassi/gotop#188]

I am using the latest copy available on Arch [AUR](https://aur.archlinux.org/packages/gotop/) - which is gotop 3.5.1-1 from https://github.com/xxxserxxx/gotop (aka this repo)

I opened the issue on the wrong repo, was google search result.
Anyway, here you go:

I opened gotop just for fun.
I formatted /dev/sdd1 (mounted on /mnt/external in the screenshot below) freshly as a 1.8TB big hard drive.
In the overview it cleary says it is used 0% and has 1 TB free. I expected it to round up to 2TB instead of down to 1TB.

Required information:

- gotop version (`gotop -V`): 3.5.1 [was 3.5.0]
- The output of `uname -a`: `Linux astolfo 5.6.4-arch1-1 #1 SMP PREEMPT Mon, 13 Apr 2020 12:21:19 +0000 x86_64 GNU/Linux` [was 5.6.2-arch1-2]
- Terminal emulator (e.g. iTerm or gnome terminal): alacritty
- Any relevenat hardware info: the hard drive in question (sdd1) is 1.8TB of size
- tmux version if using tmux: -

![image](https://user-images.githubusercontent.com/196108/79272225-6eaeb800-7ea1-11ea-9cbb-168ee5247adc.png)

```
Disk /dev/sdd: 1,84 TiB, 2000398934016 bytes, 3907029168 sectors
Disk model: WDC WD2003FZEX-0
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: A2364232-5354-48A4-AF01-303C36AC45D2

Device     Start        End    Sectors  Size Type
/dev/sdd1   2048 3907028991 3907026944  1,8T Linux filesystem
```

**Comment by xxxserxxx** [comment]
The fix will be included in the v3.6 release.
