### ISSUE TITLE
panic: interface conversion: interface {} is nil, not bool

### ISSUE THREAD

**Issue by thanateros** [xxxserxxx/gotop#93]
##### gotop version:
0.0.0
##### OS/Arch:
5.4.0-26-generic GNU/Linux
##### Terminal emulator: 
GNOME Terminal
##### Any relevant hardware info:
This is not a hardware issue
##### tmux version:
tmux 3.0a

Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs:
Does not exist.

Go version: `go version go1.14.2 linux/amd64`

Installed according to instructions: `go get -u github.com/xxxserxxx/gotop/cmd/gotop`

Then run it: `$ gotop`.

Output is: 

```
panic: interface conversion: interface {} is nil, not bool

goroutine 1 [running]:
main.parseArgs(0xc0000c2580, 0x0, 0x0)
        /home/spennington/go/src/github.com/xxxserxxx/gotop/cmd/gotop/main.go:112 +0x1b6a
main.run(0x0)
        /home/spennington/go/src/github.com/xxxserxxx/gotop/cmd/gotop/main.go:471 +0x153
main.main()
        /home/spennington/go/src/github.com/xxxserxxx/gotop/cmd/gotop/main.go:452 +0x34
```

**Comment by xxxserxxx** [comment]
Confirmed & replicated.

**Comment by xxxserxxx** [comment]
Ok, sorry about that.
